version: '3.9'

services:
  rabbitmq:
    image: rabbitmq-service
    build:
      context: ./rabbitmq
      dockerfile: Dockerfile
    ports:
      - 5672:5672
      - 15672:15672

  logger:
    image: logger-service
    build:
      context: ./logger
      dockerfile: Dockerfile
    ports:
      - 5001:5001

  api:
    image: fastapi-starter-api
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000

  # Data Service - sample microservice
  data-service:
    image: data-service
    build:
      context: ./services/dataservice
      dockerfile: Dockerfile
  # Add your own services here
